name: app-template-api
version: 0.1.0.0
description: API for application template

dependencies:
  - base >= 4.7 && < 5
  - scotty
  - aeson
  - wai-cors
  - text
  - bytestring
  - http-types
  - mtl
  - containers
  - unordered-containers

executables:
  app-template-api:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
